### ISSUE TITLE
browser scroll bar still active

### ISSUE THREAD

**Issue by muhammadcahya** [makotot/sidebar#1]
Thanks for great plugin
Is the browser scroll bar can be active also when the sidebar menu appear ?

**Comment by makotot** [comment]
For now, it cannot be active browser scrollbar.
In the next release, I'll add an option that can show browser scrollbar when the sidebar opens.

**Comment by makotot** [comment]
Now, 5ac0441ce25db1045b60775cf68a23df43b47f9a v0.0.7 has the option for browser scrollbar.
