### ISSUE TITLE
Close menu with JS

### ISSUE THREAD

**Issue by BeerBelly** [makotot/sidebar#4]
Hi,

how would I go about closing the menu with a JS call? Can you help me with it please.

Thank you.

**Comment by makotot** [comment]
Sorry for late reply.
For now, Unfortunately, this library does not provide public method.
I'll add it.

**Comment by makotot** [comment]
v0.2.0 provides public method. Please use it like below.

``` js
$('your-nav').sidebar();

// Call public `push()` method. like below.
$('trigger-elem').data('sidebar').push();
```
