### ISSUE TITLE
Transition issue

### ISSUE THREAD

**Issue by BeerBelly** [makotot/sidebar#5]
Hi,

I implemented your plugin here: wasup.si (page is a work in progress) and I'm having issues with transmissions. If you call the menu by clicking on the menu link in the top right corner it shows the sidebar but without transitions (it also doesn't close it, probably because the transitionEnd trigger never triggers).

Can you maybe show me what I'm doing wrong?

**Comment by makotot** [comment]
Probably, to make it work with transition, you need to add `jsc-sidebar-pulled` class to the element that has `jsc-sidebar-content` in your html.

**Comment by BeerBelly** [comment]
That did work. Thank you.
